[build]
  publish = "frontend"
  command = "echo 'Frontend is already built - static files'"

[[redirects]]
  from = "/api/*"
  to = "https://web-production-e5f3c.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200