[build]
  publish = "frontend"
  command = "echo 'Frontend is already built - static files'"

[[redirects]]
  from = "/api/*"
  to = "https://your-app.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200